---
title: "6mBrain_fems"
author: "Karissa Barthelson"
date: "2023-05-01"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r}
x.adult <-  read_rds("data/R_objects/adult_brain/dge.rds")
logCPM.adult <-  read_rds("data/R_objects/adult_brain/logcpm.rds")
toptables_cqn.adult <-  read_rds("data/R_objects/adult_brain/toptablescqn.rds")
hmp.fry.adult <-   read_rds("data/R_objects/adult_brain/hmp_kegg.rds") %>% 
  mutate(coef = case_when(
    grepl(coef, pattern = "MPS") ~ "MPS-IIIB", 
    grepl(coef, pattern = "EOf") ~ "EOfAD-like"
  )) 
hmp.ire.adult <-  read_rds("data/R_objects/adult_brain/hmp_ire.rds")

ireGenes <- readRDS("data/gene_sets/zebrafishireGenes.rds") %>% 
  unlist() %>% 
  as.data.frame() %>% 
  rownames_to_column("ire") %>% 
  as_tibble() %>% 
  mutate(ire = str_extract(ire, pattern = "ire[:digit:]_[:alpha:]+")) %>% 
  set_colnames(c("ire", "gene_id")) %>% 
  dplyr::filter(gene_id %in% rownames(x.adult)) %>% 
  split(f = .$ire) %>% 
  lapply(magrittr::extract2,"gene_id") 
```

# extract the fem samples
```{r}
females <- x.adult$samples %>% 
  dplyr::filter(sex == "F") %>% 
  rownames()

x.fems <- x.adult[,females]


```

# run DE analysis
```{r}
# prep a new design matrix
design.female <- model.matrix(~Genotype, data = x.fems$samples) %>% 
  set_colnames(gsub(colnames(.), pattern = "Genotype", replacement = ""))

# fit glm
fit.fem.cqn <- x.fems %>% 
  estimateDisp(design.female) %>% 
  glmFit(design.female)

toptable.fem.cqm <- design.female %>% colnames() %>% .[2:3] %>%
  sapply(function(x){
    glmLRT(fit.fem.cqn, coef = x) %>%
      topTags(n = Inf) %>%
      .[["table"]] %>%
      as_tibble() %>%
      arrange(PValue) %>%
       mutate(
        coef = x,
        DE = FDR < 0.05
      ) %>% 
      dplyr::select(
        gene_name, logFC, logCPM, PValue, FDR, DE, everything()  
      )
      
  }, simplify = FALSE)
```

```{r}
design.female %>% colnames() %>% .[2:3] %>% 
  sapply(function(y) {
    logCPM.adult[,females] %>% 
      fry(
        index = ireGenes,
        design = design.female, 
        contrast = y, 
        sort = "directional"
      ) %>% 
      rownames_to_column("pathway") %>% 
      as_tibble() %>% 
      mutate(coef = y)
  }, simplify = FALSE)

design.female %>% colnames() %>% .[2:3] %>% 
  sapply(function(y) {
    logCPM.adult[,females] %>% 
      camera(
        index = ireGenes,
        design = design.female, 
        contrast = y, 
      ) %>% 
      rownames_to_column("pathway") %>% 
      as_tibble() %>% 
      mutate(coef = y)
  }, simplify = FALSE)
```

```{r}
runHMP(gene.set.obj = ireGenes, 
       design = design.female, 
       logCPM.df = logCPM.adult[,females], 
       toptable = toptable.fem.cqm)
```



